import './globals.css';
import { Inter } from 'next/font/google';
import AuthProvider from '../context/AuthContext';
const inter = Inter({ subsets: ['latin'] });
import { Toaster } from 'react-hot-toast';
import Component from '../components/login-btn';
import { StoreProvider } from '../store/StoreProvider';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <StoreProvider>
            <div className="bg-gray-500 h-full">
              <div className="fixed w-full p-4 bg-slate-600 z-50 border-b border-red-400">
                <Component />
              </div>
              <div className="flex flex-col items-center justify-center">
                {/* //?hydration حتى لا يحدث خظأ الchildren قبل ال Toaster هنا انتبه تم وضع
                 */}
                <Toaster />
                {children}
              </div>
            </div>
          </StoreProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
