import './globals.css';
import { Inter } from 'next/font/google';
import AuthProvider from '../context/AuthContext';
const inter = Inter({ subsets: ['latin'] });
import { Toaster } from 'react-hot-toast';
import Component from '../components/login-btn';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {/* //?hydration حتى لا يحدث خظأ الchildren قبل ال Toaster هنا انتبه تم وضع /
           */}
          <Toaster />
          <Component />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
